name: "nbsphinx publisher"
# via: https://github.com/s-weigand/nbsphinx/blob/gh-action-ci-switch/.github/workflows/test.yml
on:
  push:
    branches:
      - master
jobs:
          
  nbsphinx-publish:
    #if: (contains(github.event.commits[0].message, '--publish'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
          conda-channels: conda-forge
           
      - name: Install dependencies
        run: |
          echo $(conda info)
          conda install -y pandoc librsvg tectonic
          python -m pip install sphinx
          python -m pip install nbsphinx
          python -m pip install jupytext
          (test -f requirements.txt && python -m pip install -r requirements.txt) || echo "No other requirements." 
      #- name: Show installed dependencies
      #  if: always()
      #  run: |
      #    python --version
      #    python -c "import nbsphinx; print('nbsphinx.__version__==', nbsphinx.__version__)"
      #    pandoc -v
      #    pip freeze
  
      # This is a no-cache approach; we really should be doing this in a build dir
      # pulling updates from master, rebuilding, then saving the build files.
      - name: Build docs HTML
        run: python -m sphinx . ./_build/html/ -b html

      - name: Deploy HTML site to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html

